import { Injectable, signal } from '@angular/core';

import { CarModel } from '../shared/car.model';

@Injectable({
  providedIn: 'root',
})
export class CarRentalService {
  private cars = signal<CarModel[]>([
    {
      id: '1',
      name: 'BMW X5',
      model: 2023,
      img: '../../../assets/Car-data/BMW X5-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Diesel',
      carType: 'Luxury SUV',
      ratings: 4.8,
      availabilty: 'Available',
      price: 220,
      priceCalc: '₹220/hr',
      location: 'Delhi',
      luxury: true,
      images: [
        '../../../assets/Car-data/BMW X5-1.jpg',
        '../../../assets/Car-data/BMW X5-2.jpg',
        '../../../assets/Car-data/BMW X5-3.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A luxury SUV ideal for premium city travel or business trips, offering a smooth ride, spacious cabin, and advanced comfort. It delivers a quiet and refined driving experience suited for long hours on the road. The blend of strong performance and cutting-edge tech makes it an excellent choice for premium renters.',
      features: [
        'Panoramic Sunroof',
        'Heated Seats',
        '360° Camera',
        'Premium Audio System',
        'Adaptive Cruise Control',
        'Wireless Apple CarPlay',
      ],

      mileage: '13 km/l',
      insuranceIncluded: true,
      extraFees: 'Luxury deposit required',
      hostName: 'Aman Khurana',
      hostLocation: 'H-56, South Extension Part 1, New Delhi, Delhi 110049',
    },
    {
      id: '2',
      name: 'Audi A6',
      model: 2022,
      img: '../../../assets/Car-data/Audi A6-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Luxury Sedan',
      ratings: 4.7,
      availabilty: 'Available',
      price: 200,
      priceCalc: '₹200/hr',
      location: 'Mumbai',
      luxury: true,
      images: [
        '../../../assets/Car-data/Audi A6-1.jpg',
        '../../../assets/Car-data/Audi A6-2.jpg',
        '../../../assets/Car-data/Audi A6-3.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A refined luxury sedan perfect for long-distance rentals, business travel, and premium city rides with excellent comfort. The cabin insulation ensures a peaceful driving environment even in busy city traffic. Its balanced performance and plush interior elevate every journey to a premium level.',
      features: [
        'Matrix LED Headlights',
        'Premium Leather Interior',
        'Parking Assist',
        'Adaptive Suspension',
        'Connected Navigation',
      ],

      mileage: '14 km/l',
      insuranceIncluded: true,
      extraFees: 'Premium insurance fee applies',
      hostName: 'Imran Shaikh',
      hostLocation: 'Flat 304, Rosewood Apartments, Bandra West, Mumbai, Maharashtra 400050',
    },
    {
      id: '3',
      name: 'Toyota Corolla',
      model: 2021,
      img: '../../../assets/Car-data/Toyota Corolla-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Sedan',
      ratings: 4.5,
      availabilty: 'Available',
      price: 60,
      priceCalc: '₹60/hr',
      location: 'Chennai',
      luxury: false,
      images: [
        '../../../assets/Car-data/Toyota Corolla-1.jpg',
        '../../../assets/Car-data/Toyota Corolla-2.jpg',
        '../../../assets/Car-data/Toyota Corolla-3.jpg',
      ],
      deliveryType: 'Self Pickup',
      description:
        'A reliable, fuel-efficient sedan ideal for daily rentals, city commutes, and comfortable long trips. It offers a calm driving experience with smooth suspension tuned for Indian roads. The interior ergonomics and practicality make it an excellent choice for renters seeking comfort and ease of use.',
      features: [
        'Reverse Camera',
        'Touchscreen Display',
        'Cruise Control',
        'Eco Driving Mode',
        'Rear AC Vents',
      ],

      mileage: '20 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Joseph Raj',
      hostLocation: '12/8, Anna Salai Main Road, Teynampet, Chennai, Tamil Nadu 600018',
    },
    {
      id: '4',
      name: 'Nissan Patrol',
      model: 2019,
      img: '../../../assets/Car-data/Nissan Patrol-1.jpg',
      transmission: 'Automatic',
      seater: '7',
      fuelType: 'Petrol',
      carType: 'Full-size SUV',
      ratings: 4.6,
      availabilty: 'Available',
      price: 240,
      priceCalc: '₹240/hr',
      location: 'Hyderabad',
      luxury: true,
      images: [
        '../../../assets/Car-data/Nissan Patrol-1.jpg',
        '../../../assets/Car-data/Nissan Patrol-2.jpg',
        '../../../assets/Car-data/Nissan Patrol-3.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A spacious luxury SUV perfect for group travel, long road trips, and premium outstation journeys. Its commanding road presence and plush ride quality ensure a confident and enjoyable drive. The Patrol’s powerful engine and roomy interior make it ideal for travellers who value both comfort and capability.',
      features: [
        '7-Seater Space',
        'Premium Leather Interior',
        '4x4 Mode',
        'Terrain Management System',
        'Premium Surround Sound',
      ],
      mileage: '10 km/l',
      insuranceIncluded: true,
      extraFees: 'High security deposit required',
      hostName: 'Syed Rahman',
      hostLocation: 'Plot 22, Jubilee Hills Road No. 5, Hyderabad, Telangana 500033',
    },
    {
      id: '5',
      name: 'Kia Sportage',
      model: 2023,
      img: '../../../assets/Car-data/Kia Sportage-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'SUV',
      ratings: 4.4,
      availabilty: 'Available',
      price: 90,
      priceCalc: '₹90/hr',
      location: 'Bangalore',
      luxury: false,
      images: [
        '../../../assets/Car-data/Kia Sportage-1.jpg',
        '../../../assets/Car-data/Kia Sportage-2.jpg',
        '../../../assets/Car-data/Kia Sportage-3.jpg',
      ],
      deliveryType: 'Self Pickup',
      description:
        'A stylish compact SUV great for family trips, weekend getaways, and comfortable city driving. It offers a refined suspension setup that manages bumps effortlessly. With its modern cabin and smooth driving feel, it provides an enjoyable experience for renters in all scenarios.',
      features: [
        'Touchscreen Display',
        'Rear Camera',
        'Sunroof',
        'Smart Key Entry',
        'Wireless Charging',
      ],

      mileage: '15 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Samuel D’Souza',
      hostLocation: '32, Church Street, MG Road, Bengaluru, Karnataka 560001',
    },
    {
      id: '6',
      name: 'Mercedes-Benz S-Class',
      model: 2023,
      img: '../../../assets/Car-data/Mercedes-Benz S-Class-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Luxury Sedan',
      ratings: 5.0,
      availabilty: 'Available',
      price: 350,
      priceCalc: '₹350/hr',
      location: 'Chennai',
      luxury: true,
      images: [
        '../../../assets/Car-data/Mercedes-Benz S-Class-1.jpg',
        '../../../assets/Car-data/Mercedes-Benz S-Class-2.jpg',
        '../../../assets/Car-data/Mercedes-Benz S-Class-3.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A top-tier luxury sedan ideal for VIP travel, events, weddings, and premium chauffeur rides. It delivers exceptional ride comfort with world-class cabin refinement that sets a new benchmark in luxury travel. The S-Class offers a serene driving experience designed for passengers who expect the finest in elegance and technology.',
      features: [
        'Massage Seats',
        'Ambient Lighting',
        'Premium Sound System',
        'Rear Seat Recliner',
        'Soft Close Doors',
      ],
      mileage: '11 km/l',
      insuranceIncluded: true,
      extraFees: 'High luxury deposit required',
      hostName: 'Varshini Samuel',
      hostLocation: 'N0:08,Sakthivel Nagar Main Road,Ambattur,Chennai-600062',
    },
    {
      id: '7',
      name: 'Maruti Suzuki Swift',
      model: 2020,
      img: '../../../assets/Car-data/Maruti Suzuki Swift-1.jpg',
      transmission: 'Manual',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Hatchback',
      ratings: 4.2,
      availabilty: 'Available',
      price: 45,
      priceCalc: '₹45/hr',
      location: 'Mumbai',
      luxury: false,
      images: [
        '../../../assets/Car-data/Maruti Suzuki Swift-1.jpg',
        '../../../assets/Car-data/Maruti Suzuki Swift-2.jpg',
        '../../../assets/Car-data/Maruti Suzuki Swift-3.jpg',
      ],
      deliveryType: 'Self Pickup',
      description:
        'A compact hatchback ideal for budget-friendly city rentals and short-distance travel. It offers a light, agile driving feel that makes navigating through urban traffic effortless. The Swift’s balance of efficiency and reliability ensures a smooth and stress-free rental experience.',
      features: ['ABS', 'Dual Airbags', 'Bluetooth Music', 'Fast AC', 'Steering Controls'],
      mileage: '20 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Carlos Fernandes',
      hostLocation: 'Villa 7, New Ring Road, Vasai West, Mumbai, Maharashtra 401202',
    },
    {
      id: '8',
      name: 'Hyundai Creta',
      model: 2022,
      img: '../../../assets/Car-data/Hyundai Creta-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Diesel',
      carType: 'SUV',
      ratings: 4.6,
      availabilty: 'Available',
      price: 95,
      priceCalc: '₹95/hr',
      location: 'Bangalore',
      luxury: false,
      images: [
        '../../../assets/Car-data/Hyundai Creta-1.jpg',
        '../../../assets/Car-data/Hyundai Creta-2.jpg',
        '../../../assets/Car-data/Hyundai Creta-3.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A popular SUV perfect for family trips, daily use, or comfortable long-distance travel. It delivers a refined ride suited for both highways and busy city roads. The Creta’s well-appointed cabin provides a premium feel, making every journey relaxing and enjoyable.',
      features: [
        'Sunroof',
        'Touchscreen',
        'Reverse Camera',
        'Ventilated Seats',
        'Wireless Charging',
      ],
      mileage: '17 km/l',
      insuranceIncluded: true,
      extraFees: 'Cleaning fee may apply',
      hostName: 'Azeem Khan',
      hostLocation: '45, HSR Layout Sector 2, Bengaluru, Karnataka 560102',
    },
    {
      id: '9',
      name: 'Honda City',
      model: 2019,
      img: '../../../assets/Car-data/Honda City-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Sedan',
      ratings: 4.7,
      availabilty: 'Available',
      price: 80,
      priceCalc: '₹80/hr',
      location: 'Chennai',
      luxury: false,
      images: [
        '../../../assets/Car-data/Honda City-1.jpg',
        '../../../assets/Car-data/Honda City-2.jpg',
        '../../../assets/Car-data/Honda City-3.jpg',
      ],
      deliveryType: 'Self Pickup',
      description:
        'A premium sedan perfect for business rentals, city drives, and smooth long-distance travel. It offers a refined cabin with excellent ride comfort, making it ideal for extended journeys. The City’s smooth performance and premium interior feel elevate everyday driving.',
      features: [
        'Cruise Control',
        'Android Auto',
        'Airbags',
        'Lane Watch Camera',
        'Push Button Start',
      ],
      mileage: '18 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Denzel Antony',
      hostLocation: 'Door No. 9, Besant Avenue Road, Adyar, Chennai, Tamil Nadu 600020',
    },
    {
      id: '10',
      name: 'Range Rover Velar',
      model: 2020,
      img: '../../../assets/Car-data/Range Rover Velar-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Diesel',
      carType: 'Luxury SUV',
      ratings: 4.9,
      availabilty: 'Available',
      price: 260,
      priceCalc: '₹260/hr',
      location: 'Hyderabad',
      luxury: true,
      images: [
        '../../../assets/Car-data/Range Rover Velar-1.jpg',
        '../../../assets/Car-data/Range Rover Velar-2.jpg',
        '../../../assets/Car-data/Range Rover Velar-3.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A luxury SUV ideal for premium outstation trips, business travel, and high-class rental experiences. The Velar combines striking design with a plush, quiet cabin that enhances every drive. Its refined performance and advanced features ensure a superior travel experience for luxury-focused renters.',
      features: [
        'Panoramic Roof',
        'Ventilated Seats',
        '360 Camera',
        'Adaptive Terrain Control',
        'Heads-Up Display',
      ],
      mileage: '14 km/l',
      insuranceIncluded: true,
      extraFees: 'Premium security deposit required',
      hostName: 'Faisal Qureshi',
      hostLocation: 'House 19-4-5, Charminar Road, Old City, Hyderabad, Telangana 500002',
    },
    {
      id: '11',
      name: 'Tata Nexon',
      model: 2021,
      img: '../../../assets/Car-data/Tata Nexon -1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Compact SUV',
      ratings: 4.5,
      availabilty: 'Available',
      price: 60,
      priceCalc: '₹60/hr',
      location: 'Delhi',
      luxury: false,
      images: [
        '../../../assets/Car-data/Tata Nexon -1.jpg',
        '../../../assets/Car-data/Tata Nexon -2.jpg',
        '../../../assets/Car-data/Nexon-interior.jpg',
      ],
      deliveryType: 'Self Pickup',
      description:
        'A safe and feature-rich compact SUV perfect for city rentals, daily travel, and family usage. Its strong build and comfortable ride quality provide confidence on every drive. The Nexon’s modern features and smooth performance make it a dependable choice for renters.',
      features: ['Sunroof', 'ESP', 'Harman Audio', 'Hill Hold Assist', 'Connected Car Features'],
      mileage: '17 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Gurpreet Singh',
      hostLocation: 'C-12, Punjabi Bagh West, New Delhi, Delhi 110026',
    },
    {
      id: '12',
      name: 'Skoda Octavia',
      model: 2022,
      img: '../../../assets/Car-data/Skoda Octavia-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Sedan',
      ratings: 4.8,
      availabilty: 'Available',
      price: 110,
      priceCalc: '₹110/hr',
      location: 'Pune',
      luxury: false,
      images: [
        '../../../assets/Car-data/Skoda Octavia-1.jpg',
        '../../../assets/Car-data/Skoda Octavia-2.jpg',
        '../../../assets/Car-data/Skoda-Ocatvia-interior.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A premium European sedan ideal for comfortable long-distance travel and executive rentals. It delivers a smooth, stable driving experience that keeps passengers relaxed even on extended journeys. The Octavia’s refined interior and advanced features make it a standout choice in its segment.',
      features: ['Virtual Cockpit', 'Ambient Lights', 'Auto Park Assist', 'Memory Seats'],
      mileage: '16 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Faizal Kazi',
      hostLocation: 'Flat 2B, Clover Highlands, NIBM Road, Pune, Maharashtra 411048',
    },
    {
      id: '13',
      name: 'Toyota Fortuner',
      model: 2021,
      img: '../../../assets/Car-data/Toyota Fortuner-1.jpg',
      transmission: 'Automatic',
      seater: '7',
      fuelType: 'Diesel',
      carType: 'SUV',
      ratings: 4.8,
      availabilty: 'Available',
      price: 180,
      priceCalc: '₹180/hr',
      location: 'Ahmedabad',
      luxury: false,
      images: [
        '../../../assets/Car-data/Toyota Fortuner-1.jpg',
        '../../../assets/Car-data/Toyota Fortuner-2.jpg',
        '../../../assets/Car-data/toyota-fortuner-interior.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A powerful SUV perfectly suited for long highway trips, hill-station drives, or group travel. Its strong build and high seating position provide a commanding driving feel. The Fortuner’s dependable performance ensures a smooth and confident experience on every terrain.',
      features: ['4x4 Mode', 'Premium Seats', 'Rear AC', 'Hill Descent Control'],
      mileage: '12 km/l',
      insuranceIncluded: true,
      extraFees: 'Security deposit applies',
      hostName: 'Ronak Christian',
      hostLocation: '23, Shanti Nagar Society, Maninagar, Ahmedabad, Gujarat 380008',
    },
    {
      id: '14',
      name: 'Mahindra Thar',
      model: 2023,
      img: '../../../assets/Car-data/Mahindra Thar-1.jpg',
      transmission: 'Manual',
      seater: '4',
      fuelType: 'Diesel',
      carType: 'Offroad SUV',
      ratings: 4.9,
      availabilty: 'Available',
      price: 130,
      priceCalc: '₹130/hr',
      location: 'Goa',
      luxury: false,
      images: [
        '../../../assets/Car-data/Mahindra Thar-1.jpg',
        '../../../assets/Car-data/Mahindra Thar-2.jpg',
        '../../../assets/Car-data/Mahindra Thar-3.jpg',
      ],
      deliveryType: 'Self Pickup',
      description:
        'An off-road SUV ideal for adventure rentals, beach trips, and rugged terrain experiences. It offers a bold driving feel with strong capability for challenging routes. The Thar’s open-air charm and sturdy build provide a unique and thrilling rental experience.',
      features: [
        '4x4 Drive',
        'Touchscreen',
        'Roll-Cage',
        'Water Resistant Cabin',
        'Off-road Mode Selector',
      ],
      mileage: '13 km/l',
      insuranceIncluded: true,
      extraFees: 'Offroad usage fee may apply',
      hostName: 'Allan Rodrigues',
      hostLocation: 'House No. 145, Baga Road, Calangute, Goa 403516',
    },
    {
      id: '14',
      name: 'Mercedes-Benz C-Class',
      model: 2020,
      img: '../../../assets/Car-data/Mercedes-Benz S-Class-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Luxury Sedan',
      ratings: 4.9,
      availabilty: 'Available',
      price: 200,
      priceCalc: '₹200/hr',
      location: 'Delhi',
      luxury: true,
      images: [
        '../../../assets/Car-data/Mercedes-Benz S-Class-1.jpg',
        '../../../assets/Car-data/Mercedes-Benz S-Class-2.jpg',
        '../../../assets/Car-data/Mercedes-Benz S-Class-3.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A luxury sedan great for corporate rentals, airport transfers, and premium daily travel. It offers a refined balance of comfort and performance that enhances every journey. The C-Class delivers a polished driving experience ideal for those seeking everyday luxury.',
      features: ['Ambient Lighting', 'Sunroof', 'Memory Seats', 'Wireless Smartphone Integration'],
      mileage: '14 km/l',
      insuranceIncluded: true,
      extraFees: 'Luxury security deposit required',
      hostName: 'Mohammed Arif',
      hostLocation: 'D-34, Zakir Nagar, Okhla, New Delhi, Delhi 110025',
    },
    {
      id: '16',
      name: 'Volkswagen Polo',
      model: 2022,
      img: '../../../assets/Car-data/Volkswagen Polo -1.jpg',
      transmission: 'Manual',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Hatchback',
      ratings: 4.4,
      availabilty: 'Available',
      price: 50,
      priceCalc: '₹50/hr',
      location: 'Hyderabad',
      luxury: false,
      images: [
        '../../../assets/Car-data/Volkswagen Polo -1.jpg',
        '../../../assets/Car-data/Volkswagen Polo -2.jpg',
        '../../../assets/Car-data/Volkswagen Polo -3.jpg',
      ],
      deliveryType: 'Self Pickup',
      description:
        'A sporty and compact hatchback perfect for solo city travel and short weekend trips. It offers sharp handling and a confident drive that appeals to enthusiasts. The Polo’s solid build quality and refined road manners make it a dependable rental choice.',
      features: ['ABS', 'Premium Audio', 'Multi-function Steering', 'Sport Mode'],
      mileage: '18 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Yusuf Pasha',
      hostLocation: 'Flat 502, Green Meadows Residency, Gachibowli, Hyderabad, Telangana 500032',
    },
    {
      id: '17',
      name: 'BMW 3 Series',
      model: 2023,
      img: '../../../assets/Car-data/BMW 3 Series-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Diesel',
      carType: 'Luxury Sedan',
      ratings: 4.8,
      availabilty: 'Available',
      price: 210,
      priceCalc: '₹210/hr',
      location: 'Bangalore',
      luxury: true,
      images: [
        '../../../assets/Car-data/BMW 3 Series-1.jpg',
        '../../../assets/Car-data/BMW 3 Series-2.jpg',
        '../../../assets/Car-data/BMW 3 Series-3.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A sporty luxury sedan ideal for premium rentals, business trips, and spirited long drives. It delivers precise handling with a dynamic yet comfortable ride that enhances highway performance. The 3 Series provides a refined driving atmosphere suited for renters who enjoy both comfort and sportiness.',
      features: ['iDrive System', 'Memory Seats', 'Sport Suspension', 'Heads-Up Display'],
      mileage: '16 km/l',
      insuranceIncluded: true,
      extraFees: 'High security deposit applies',
      hostName: 'Christopher Mathew',
      hostLocation: 'No. 78, Indiranagar 2nd Stage, Bengaluru, Karnataka 560038',
    },
    {
      id: '18',
      name: 'Kia Carens',
      model: 2021,
      img: '../../../assets/Car-data/Kia Carens-1.jpg',
      transmission: 'Automatic',
      seater: '7',
      fuelType: 'Petrol',
      carType: 'MPV',
      ratings: 4.6,
      availabilty: 'Available',
      price: 75,
      priceCalc: '₹75/hr',
      location: 'Chennai',
      luxury: false,
      images: [
        '../../../assets/Car-data/Kia Carens-1.jpg',
        '../../../assets/Car-data/Kia Carens-2.jpg',
        '../../../assets/Car-data/Kia-Carens-interior.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A comfortable 7-seater perfect for family rentals, outstation road trips, and group travel. Its spacious cabin and smooth suspension ensure a pleasant journey for all passengers. The Carens provides a refined travel experience suited for long hours on the road.',
      features: ['Captain Seats', 'Rear AC', '6 Airbags', 'Smart Air Purifier'],
      mileage: '15 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Abdul Khader',
      hostLocation: '27/10, Mount Road, Guindy, Chennai, Tamil Nadu 600032',
    },
    {
      id: '19',
      name: 'Tesla Model 3',
      model: 2023,
      img: '../../../assets/Car-data/Tesla-Model-3--1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Electric',
      carType: 'Electric Sedan',
      ratings: 4.9,
      availabilty: 'Available',
      price: 300,
      priceCalc: '₹300/hr',
      location: 'Mumbai',
      luxury: true,
      images: [
        '../../../assets/Car-data/Tesla-Model-3--1.jpg',
        '../../../assets/Car-data/Tesla Model 3-2.jpg',
        '../../../assets/Car-data/Tesla-Model-3-Interior.jpg',
      ],
      deliveryType: 'Door Delivery',
      description:
        'A futuristic electric sedan ideal for silent luxury travel, city rides, and eco-friendly long trips. Its instant acceleration and quiet cabin create a smooth, modern driving experience. The Model 3’s advanced technology and premium comfort make it a standout choice for tech-savvy renters.',
      features: ['Autopilot', 'Glass Roof', 'Premium Connectivity', 'Fast Charging Support'],
      mileage: '520 km range',
      insuranceIncluded: true,
      extraFees: 'EV charging fees apply',
      hostName: 'Reuben Masih',
      hostLocation: 'Flat 11C, Sea Breeze Towers, Juhu Tara Road, Mumbai, Maharashtra 400049',
    },
    {
      id: '20',
      name: 'Hyundai i20',
      model: 2022,
      img: '../../../assets/Car-data/Hyundai i20-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Hatchback',
      ratings: 4.5,
      availabilty: 'Available',
      price: 55,
      priceCalc: '₹55/hr',
      location: 'Pune',
      luxury: false,
      images: [
        '../../../assets/Car-data/Hyundai i20-1.jpg',
        '../../../assets/Car-data/Hyundai i20-2.jpg',
        '../../../assets/Car-data/Hyundai i20-3.jpg',
      ],
      deliveryType: 'Self Pickup',
      description:
        'A premium hatchback perfect for city rentals, daily commuting, and comfortable weekend trips. It delivers a smooth urban driving feel with excellent manoeuvrability. The i20’s refined cabin and modern features make it a practical and enjoyable choice for renters.',
      features: ['Touchscreen', 'Wireless CarPlay', 'Rear Camera', 'Multi-Drive Modes'],
      mileage: '19 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Sahil Shaikh',
      hostLocation: 'C-503, Orchid Residency, Wakad, Pune, Maharashtra 411057',
    },
    {
      id: '21',
      name: 'Hyundai Venue',
      model: 2025,
      img: '../../../../assets/Car-data/venue-2.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'SUV',
      ratings: 4.7,
      availabilty: 'Available',
      price: 78,
      priceCalc: '₹78/hr',
      location: 'Kochi',
      luxury: false,
      images: [
        '../../../../assets/Car-data/venue-2.jpg',
        '../../../../assets/Car-data/Hyundai-Venue-1.webp',
        '../../../../assets/Car-data/venue-3.webp',
      ],
      deliveryType: 'Home Delivery',
      description:
        'A stylish compact SUV perfect for Kochi city drives and coastal highway trips with smooth handling and comfort.',
      features: ['Touchscreen', 'Rear Camera', 'Wireless Android Auto', 'Sunroof'],
      mileage: '20 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Rahul Krishnan',
      hostLocation: 'Edappally, Kochi, Kerala',
    },

    {
      id: '22',
      name: 'Hyundai Verna',
      model: 2019,
      img: '../../../../assets/Car-data/verna-1.avif',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Sedan',
      ratings: 4.5,
      availabilty: 'Available',
      price: 80,
      priceCalc: '₹80/hr',
      location: 'Kochi',
      luxury: false,
      images: [
        '../../../../assets/Car-data/verna-1.avif',
        '../../../../assets/Car-data/venue-2.jpg',
        '../../../../assets/Car-data/verna-3.webp',
      ],
      deliveryType: 'Self Pickup',
      description:
        'A stylish sedan offering smooth rides and premium comfort for business and leisure travel.',
      features: ['Wireless CarPlay', 'Rear Camera', 'Ventilated Seats'],
      mileage: '20 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Nithin Joseph',
      hostLocation: 'Edappally, Kochi',
    },
    {
      id: '23',
      name: 'Toyota Fortuner',
      model: 2024,
      img: '../../../assets/Car-data/Toyota Fortuner-1.jpg',
      transmission: 'Automatic',
      seater: '7',
      fuelType: 'Diesel',
      carType: 'SUV',
      ratings: 4.7,
      availabilty: 'Available',
      price: 150,
      priceCalc: '₹150/hr',
      location: 'Munnar',
      luxury: true,
      images: [
        '../../../assets/Car-data/Toyota Fortuner-1.jpg',
        '../../../assets/Car-data/Toyota Fortuner-2.jpg',
        '../../../assets/Car-data/toyota-fortuner-interior.jpg',
      ],
      deliveryType: 'Self Pickup',
      description:
        'A powerful luxury SUV ideal for long hill drives, family trips, and premium comfort in Munnar.',
      features: ['4x4', 'Leather Seats', 'Cruise Control', 'Touchscreen'],
      mileage: '14 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Rohit Varma',
      hostLocation: 'Munnar Town, Kerala',
    },

    {
      id: '24',
      name: 'Maruti Baleno',
      model: 2025,
      img: '../../../../assets/Car-data/baleno-1.webp',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Hatchback',
      ratings: 4.4,
      availabilty: 'Available',
      price: 60,
      priceCalc: '₹60/hr',
      location: 'Ooty',
      luxury: false,
      images: [
        '../../../../assets/Car-data/baleno-1.webp',
        '../../../../assets/Car-data/baleno-2.jpg',
        '../../../../assets/Car-data/Maruti-Suzuki-Baleno-Interior.avif',
      ],
      deliveryType: 'Self Pickup',
      description: 'A smooth hatchback ideal for hill station drives and city roaming.',
      features: ['Touchscreen', 'Rear Camera', 'Steering Controls'],
      mileage: '22 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Karthik R',
      hostLocation: 'Charing Cross, Ooty',
    },
    {
      id: '25',
      name: 'Tata Tiago EV',
      model: 2023,
      img: '../../../../assets/Car-data/tiago-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Electric',
      carType: 'Hatchback',
      ratings: 4.7,
      availabilty: 'Available',
      price: 65,
      priceCalc: '₹65/hr',
      location: 'Coimbatore',
      luxury: false,
      images: [
        '../../../../assets/Car-data/tiago-1.jpg',
        '../../../../assets/Car-data/Tiago-2.jpg',
        '../../../../assets/Car-data/Tiago-3.jpg',
      ],
      deliveryType: 'Home Delivery',
      description: 'Eco-friendly electric hatchback with silent drive and excellent city range.',
      features: ['Digital Cluster', 'Fast Charging', 'Touchscreen'],
      mileage: '250 km/charge',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Prakash S',
      hostLocation: 'RS Puram, Coimbatore',
    },
    {
      id: '26',
      name: 'Skoda Slavia',
      model: 2025,
      img: '../../../../assets/Car-data/skoda-slaiva-1.jpg',
      transmission: 'Automatic',
      seater: '5',
      fuelType: 'Petrol',
      carType: 'Sedan',
      ratings: 4.6,
      availabilty: 'Available',
      price: 95,
      priceCalc: '₹95/hr',
      location: 'Mysore',
      luxury: true,
      images: [
        '../../../../assets/Car-data/skoda-slaiva-1.jpg',
        '../../../../assets/Car-data/skoda-slavia-2.webp',
        '../../../../assets/Car-data/Skoda_Slavia_interior.jpg',
      ],
      deliveryType: 'Home Delivery',
      description: 'Luxury sedan offering premium comfort, performance and elegant styling.',
      features: ['Sunroof', 'Digital Cluster', 'Wireless CarPlay'],
      mileage: '19 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Suresh Gowda',
      hostLocation: 'Vijayanagar, Mysore',
    },
    {
      id: '27',
      name: 'Tata Safari',
      model: 2023,
      img: '../../../../assets/Car-data/safari-1.webp',
      transmission: 'Automatic',
      seater: '7',
      fuelType: 'Diesel',
      carType: 'SUV',
      ratings: 4.6,
      availabilty: 'Available',
      price: 135,
      priceCalc: '₹135/hr',
      location: 'Bangalore',
      luxury: true,
      images: [
        '../../../../assets/Car-data/safari-1.webp',
        '../../../../assets/Car-data/tata-safari-2.jpg',
        '../../../../assets/Car-data/safari-3.webp',
      ],
      deliveryType: 'Self Pickup',
      description:
        'Premium SUV ideal for long city drives, highway trips, and luxury family travel across Bangalore.',
      features: ['Panoramic Sunroof', 'Ventilated Seats', 'Touchscreen'],
      mileage: '16 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Akash Reddy',
      hostLocation: 'Whitefield, Bangalore, Karnataka',
    },
    {
      id: '28',
      name: 'Maruti Jimny',
      model: 2021,
      img: '../../../../assets/Car-data/jimny_2.jpg',
      transmission: 'Manual',
      seater: '4',
      fuelType: 'Petrol',
      carType: 'SUV',
      ratings: 4.5,
      availabilty: 'Available',
      price: 95,
      priceCalc: '₹95/hr',
      location: 'Chennai',
      luxury: false,
      images: [
        '../../../../assets/Car-data/jimny_2.jpg',
        '../../../../assets/Car-data/jimny_2.jpg',
        '../../../../assets/Car-data/jimmy-3.webp',
      ],
      deliveryType: 'Self Pickup',
      description:
        'Compact lifestyle SUV ideal for city cruising, coastal drives, and weekend adventures around Chennai.',
      features: ['4x4', 'Hill Assist', 'Touchscreen'],
      mileage: '16 km/l',
      insuranceIncluded: true,
      extraFees: 'None',
      hostName: 'Karthik Subramanian',
      hostLocation: 'Velachery, Chennai, Tamil Nadu',
    },
  ]);

  getCarSignal() {
    return this.cars;
  }

  getCars() {
    return this.cars();
  }

  getCarsById(id: any) {
    const numberId = Number(id);
    return this.cars().find((item) => Number(item.id) === numberId);
  }

  //firebase handles loading cars now

  // onAddToWishlist(car: CarModel, firebaseId: string) {
  //   this.wishlistService.onAddCar(car, firebaseId);
  // }

  // onAddtoCheckout(car: CarModel) {
  //   this.chechoutService.addToCheckout(car);
  // }
}
